name: http_services
description: A Dart package to handle HTTP services.
version: 1.0.0
author: Antonello Galipò
homepage: https://github.com/magicleon94/http_services

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0